# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

services:
  - postgresql

before_install:
  - psql -c 'create database job4j_todo_test;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - kiril5471710@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="97bf8ab1-6e1d-4fc9-a6aa-94c01e213895"